<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>PharmacyAPI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\services\pharmacy\PharmacyAPI.PharmacyService\PharmacyAPI.PharmacyService.csproj" />
    <ProjectReference Include="..\PharmacyAPI.TestBase\PharmacyAPI.TestBase.csproj" />
  </ItemGroup>

</Project>
